planner_client:
  ros__parameters:
    plan_solver_timeout: 15.0
planner:
  ros__parameters:
    plan_solver_timeout: 15.0
    plan_solver_plugins: ["Symk"]
    POPF:
      plugin: "plansys2/POPFPlanSolver"
    TFD:
      plugin: "plansys2/TFDPlanSolver"
    Symk:
      plugin: "plansys2/SymkPlanner"
executor:
  ros__parameters:
    bt_builder_plugin: "SimpleBTBuilder"
    # bt_builder_plugin: "STNBTBuilder"
